SHOW GRANTS;
SHOW STATUS;					
SHOW ERRORS;
SHOW WARNINGS;

SHOW DATABASES;
CREATE DATABASE demo CHARSET=utf8mb4;
SHOW CREATE DATABASE demo;
DROP DATABASE demo;
USE demo;

SHOW TABLES;
SHOW CREATE TABLE user;
DROP TABLE user;
SHOW COLUMNS FROM user;
DESCRIBE user;
RENAME TABLE user TO users;
ALTER TABLE ADD age INT;
